spring:
  cloud:
    gateway:
        routes:
          - id: account-route
            uri: lb://account-service
            predicates:
              - Path=/api/account/**
            filters:
              - RewritePath=/api/account/(?<segment>.*), /$\{segment}
              - name: RouteBasedAuthFilter
                args:
                  requiredAuth: true

          - id: ai-route
            uri: lb://ai-service
            predicates:
                - Path=/api/llm/**
            filters:
              - RewritePath=/api/llm/(?<segment>.*), /$\{segment}
              - name: RouteBasedAuthFilter
                args:
                  requiredAuth: true

          - id: resource-route
            uri: lb://resource-service
            predicates:
                - Path=/api/resources/**
            filters:
              - RewritePath=/api/resources/(?<segment>.*), /$\{segment}
              - name: RouteBasedAuthFilter
                args:
                  requiredAuth: true

          - id: blog-service
            uri: lb://blog-service
            predicates:
                - Path=/api/blogs/**
            filters:
              - RewritePath=/api/blogs/(?<segment>.*), /$\{segment}
              - name: RouteBasedAuthFilter
                args:
                  requiredAuth: true
        default-filters:
          - AddResponseHeader=X-Response-Default, Default
          - RewritePath=/api/(?<segment>.*), /$\{segment}